<a href="https://colab.research.google.com/github/BimalGhimire38/PyTorch_for_deep_learning/blob/main/03_pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [135]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [136]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [137]:
df.shape

(569, 33)

In [138]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [139]:
df.shape

(569, 31)

Train test SPlit

In [140]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0],test_size=0.2)

In [141]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

Scaling

In [142]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)


In [143]:
x_train

array([[-0.90056006, -1.64574848, -0.92755001, ..., -1.265364  ,
        -1.21218987, -0.95524338],
       [ 0.45034801, -0.33816536,  0.45625772, ...,  0.99647555,
         1.45333184,  1.09979092],
       [ 1.50721859, -0.27679865,  1.54451045, ...,  1.65958026,
         1.21248119,  0.42656233],
       ...,
       [ 2.79987396,  0.20705431,  2.97008138, ...,  1.66109766,
         0.53195684, -0.22363617],
       [-0.50388685, -1.03208132, -0.56011412, ..., -1.02273141,
        -0.96164053, -1.31354881],
       [ 1.32691259,  0.46904299,  1.25939627, ...,  0.96461011,
        -0.55267934, -0.98416489]])

In [144]:
y_train

296    B
11     M
162    M
413    B
399    B
      ..
531    B
514    M
122    M
404    B
70     M
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [145]:
# Re-run train_test_split to ensure y_train and y_test are in their original categorical string format
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0],test_size=0.2)

encoder = LabelEncoder()
# Fit the encoder on all unique values from the original 'diagnosis' column
encoder.fit(df.iloc[:,0].astype(str))

y_train = encoder.transform(y_train.astype(str))
y_test = encoder.transform(y_test.astype(str))

In [146]:
y_train

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,

# Numpy Arrays to PyTorch Tensors

In [147]:
x_train_tensor = torch.from_numpy(x_train.to_numpy())
x_test_tensor = torch.from_numpy(x_test.to_numpy())
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [148]:
x_train_tensor

tensor([[1.1340e+01, 2.1260e+01, 7.2480e+01,  ..., 8.2780e-02, 2.8290e-01,
         8.8320e-02],
        [2.1090e+01, 2.6570e+01, 1.4270e+02,  ..., 2.9030e-01, 4.0980e-01,
         1.2840e-01],
        [1.1320e+01, 2.7080e+01, 7.1760e+01,  ..., 2.0830e-02, 2.8490e-01,
         7.0870e-02],
        ...,
        [1.4450e+01, 2.0220e+01, 9.4490e+01,  ..., 1.8380e-01, 4.7530e-01,
         1.0130e-01],
        [1.2670e+01, 1.7300e+01, 8.1250e+01,  ..., 5.6020e-02, 2.6880e-01,
         6.8880e-02],
        [1.3470e+01, 1.4060e+01, 8.7320e+01,  ..., 1.3350e-01, 3.2270e-01,
         9.3260e-02]], dtype=torch.float64)

In [149]:
y_train_tensor.shape

torch.Size([455])

In [150]:
x_train_tensor

tensor([[1.1340e+01, 2.1260e+01, 7.2480e+01,  ..., 8.2780e-02, 2.8290e-01,
         8.8320e-02],
        [2.1090e+01, 2.6570e+01, 1.4270e+02,  ..., 2.9030e-01, 4.0980e-01,
         1.2840e-01],
        [1.1320e+01, 2.7080e+01, 7.1760e+01,  ..., 2.0830e-02, 2.8490e-01,
         7.0870e-02],
        ...,
        [1.4450e+01, 2.0220e+01, 9.4490e+01,  ..., 1.8380e-01, 4.7530e-01,
         1.0130e-01],
        [1.2670e+01, 1.7300e+01, 8.1250e+01,  ..., 5.6020e-02, 2.6880e-01,
         6.8880e-02],
        [1.3470e+01, 1.4060e+01, 8.7320e+01,  ..., 1.3350e-01, 3.2270e-01,
         9.3260e-02]], dtype=torch.float64)

In [151]:
x_train_tensor.shape

torch.Size([455, 30])

# Defining the Model

In [152]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss


## Important parameters

In [153]:
learning_rate = 0.1
epochs = 25

## Training Pipeling

In [154]:
# create model
model = MySimpleNN(x_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(x_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')



Epoch: 1, Loss: 9.883403745855443
Epoch: 2, Loss: 9.883403745855443
Epoch: 3, Loss: 9.883403745855443
Epoch: 4, Loss: 9.883403745855443
Epoch: 5, Loss: 9.883403745855443
Epoch: 6, Loss: 9.883403745855443
Epoch: 7, Loss: 9.883403745855443
Epoch: 8, Loss: 9.883403745855443
Epoch: 9, Loss: 9.883403745855443
Epoch: 10, Loss: 9.883403745855443
Epoch: 11, Loss: 9.883403745855443
Epoch: 12, Loss: 9.883403745855443
Epoch: 13, Loss: 9.883403745855443
Epoch: 14, Loss: 9.883403745855443
Epoch: 15, Loss: 9.883403745855443
Epoch: 16, Loss: 9.883403745855443
Epoch: 17, Loss: 9.883403745855443
Epoch: 18, Loss: 9.883403745855443
Epoch: 19, Loss: 9.883403745855443
Epoch: 20, Loss: 9.883403745855443
Epoch: 21, Loss: 9.883403745855443
Epoch: 22, Loss: 9.883403745855443
Epoch: 23, Loss: 9.883403745855443
Epoch: 24, Loss: 9.883403745855443
Epoch: 25, Loss: 9.883403745855443


In [155]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)