<a href="https://colab.research.google.com/github/BimalGhimire38/PyTorch_for_deep_learning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2082/05/22  08:27 PM, @Home, Lalitpur

PyTorch Tutorial

In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Using GPU: Tesla T4


Creating a Tensor in PyTorch

In [4]:
# Using Empty
a=torch.empty(2,3)

In [5]:
# check type
type(a)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# Using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# Using rand
torch.rand(2,3)

tensor([[0.2560, 0.5633, 0.6686],
        [0.3857, 0.8839, 0.0311]])

In [9]:
# Use of seed
# for Reproduciavility



In [10]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# Other Ways

# arange
print("Using arange ->",torch.arange(0,10,2))

Using arange -> tensor([0, 2, 4, 6, 8])


In [13]:
# Using linspace
print("Using linspace ->",torch.linspace(0,10,10))

Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [14]:
# Using eye
print("Using eye ->", torch.eye(5))

Using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [15]:
# Using full
print("Using full ->",torch.full((3,3),5))

Using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [17]:
x.shape

torch.Size([2, 3])

Creating Similar tensor

In [18]:
y = torch.empty_like(x)
y

tensor([[0, 0, 0],
        [0, 1, 0]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
# as x has all integer values and rand generates float value between 0 and 1.. It will through an error
# torch.rand_like(x)

In [22]:
x.dtype

torch.int64

In [23]:
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.tensor([1,2,3,], dtype=torch.float32)

tensor([1., 2., 3.])

Changing the datatype of a datatype

In [25]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [26]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# **Mathematical Opearation in Tensors**

In [27]:
x = torch.rand(2,2)

In [28]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [29]:
# Addition
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [30]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [31]:
# Subtraction
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [32]:
# multliplication
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [33]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [34]:
# division
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [35]:
# Int Division
(x *100)//3

tensor([[23., 26.],
        [13., 30.]])

In [36]:
# mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [37]:
# Power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

# Element Wise Operation

In [38]:
a = torch.rand(2,3)
b= torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [39]:
# add
a+b
# subtract
a-b
# division
a/b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [40]:
c = torch.tensor([1,-2,3,-4])

In [41]:
# absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [42]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [43]:
d = torch.tensor([1.9,3.2,4.6,9.8])

In [44]:
# Round
torch.round(d)

tensor([ 2.,  3.,  5., 10.])

In [45]:
# Ceil
torch.ceil(d)

tensor([ 2.,  4.,  5., 10.])

In [46]:
# Floor
torch.floor(d)

tensor([1., 3., 4., 9.])

In [47]:
# Clamp
torch.clamp(d, min=4, max=5)

tensor([4.0000, 4.0000, 4.6000, 5.0000])

# Reduction Operation

In [48]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [49]:
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [50]:
# Sum
torch.sum(e)

tensor(24.)

In [51]:
# sum along column
torch.sum(e, dim=0)

tensor([ 8.,  0., 16.])

In [52]:
# sum along row
torch.sum(e, dim=1)

tensor([15.,  9.])

In [53]:
# Mean
torch.mean(e)

tensor(4.)

In [54]:
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [55]:
# Median
torch.median(e)

tensor(0.)

In [56]:
# Maximum
torch.max(e)

tensor(9.)

In [57]:
# product
torch.prod(e)

tensor(0.)

In [58]:
# Standard Deviation
torch.std(e)

tensor(4.4272)

In [59]:
# Variance
torch.var(e)

tensor(19.6000)

In [60]:
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [61]:
# argmax
torch.argmax(e)

tensor(5)

In [62]:
# argmin
torch.argmin(e)

tensor(1)

In [63]:
f = torch.randint(size=(2,3), low=0, high=10)
g= torch.randint(size=(3,2),low=0,high=10)

In [64]:
f,g

(tensor([[5, 7, 3],
         [9, 4, 0]]),
 tensor([[5, 7],
         [5, 9],
         [9, 7]]))

In [65]:
# Matrix multliplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

# Vector Operation

In [66]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])



In [67]:
v1,v2

(tensor([1, 2]), tensor([3, 4]))

In [68]:
# dot product
torch.dot(v1,v2)

tensor(11)

In [69]:
f

tensor([[5, 7, 3],
        [9, 4, 0]])

In [70]:
# Transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [71]:
i = torch.randint(size=(3,3),low=2,high=6,dtype=torch.float32)

In [72]:
i

tensor([[3., 3., 4.],
        [5., 5., 5.],
        [2., 4., 3.]])

In [73]:
# Determinant
torch.det(i)

tensor(10.)

In [74]:
# Inverse
torch.inverse(i)

tensor([[-0.5000,  0.7000, -0.5000],
        [-0.5000,  0.1000,  0.5000],
        [ 1.0000, -0.6000,  0.0000]])

[Completed upto this ](https://youtu.be/mDsFsnw3SK4?t=3008)

2082/05/23  08:16 AM

# 5. Comparision Operations

In [75]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3), low=0, high=10)
i = torch.randint(size=(2,3), low=0,high=10)

In [76]:
i,j

(tensor([[3, 3, 5],
         [0, 6, 4]]),
 tensor([[5, 0, 4],
         [3, 8, 8]]))

In [77]:
# greater than
i>j

tensor([[False,  True,  True],
        [False, False, False]])

In [78]:
i<j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [79]:
i == j

tensor([[False, False, False],
        [False, False, False]])

In [80]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

# 6. Special Functions

2082/08/24  09:32 AM, @ Har Har Mahadev

In [81]:
k = torch.randint(size=(2,3), low=0, high=10)

In [82]:
k

tensor([[0, 8, 4],
        [7, 2, 3]])

# Inplace Operation

In [83]:
m = torch.rand(2,3)
n =  torch.rand(2,3)
print(m,n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]]) tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [84]:
m+n
# when you add this way , a new tensor is created and it occupies some memory which is not
# in some case

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [85]:
m.add_(n)
# THis adds m and n , and overwrites m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [86]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [87]:
torch.relu(m)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [88]:
m.relu()

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

# Copying a Tensor


In [89]:
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [90]:
b =a
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [91]:
a[0][0]=0



In [92]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [93]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [94]:
id(a)

140267595831792

In [95]:
id(b)

140267595831792

In [96]:
b = a.clone()

In [97]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [98]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [99]:
a[0][1]=100
a



tensor([[0.0000e+00, 1.0000e+02, 4.9744e-02],
        [1.7798e-01, 3.0110e-01, 1.8930e-01]])

In [100]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [101]:
id(a), id(b)

(140267595831792, 140267595559984)

# Tensor Operations on GPU

In [102]:
torch.cuda.is_available()

True

In [105]:
device = torch.device('cuda')

In [106]:
# Creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [107]:
# moving an existing tensor to GPU
a = torch.rand(2,3)

In [108]:
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [110]:
b=a.to(device)

In [111]:
b +5

tensor([[5.9186, 5.2131, 5.3957],
        [5.6017, 5.4234, 5.5224]], device='cuda:0')

# Reshaping Tensors

In [112]:
a = torch.ones(4,4)

In [113]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [114]:
# Reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [115]:
# Flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [116]:
# Permute
b = torch.rand(2,3,4)
b

tensor([[[0.4175, 0.0340, 0.9157, 0.3079],
         [0.6269, 0.8277, 0.6594, 0.0887],
         [0.4890, 0.5887, 0.7340, 0.8497]],

        [[0.9112, 0.4847, 0.9436, 0.3904],
         [0.2499, 0.3206, 0.9753, 0.7582],
         [0.6688, 0.2651, 0.2336, 0.5057]]])

In [117]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [119]:
# unsqueeze
# Image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [120]:
# Squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy and PyTorch

In [121]:
import numpy as np

In [123]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [124]:
b = a.numpy()
b

array([1, 2, 3])

In [125]:
type(b)

numpy.ndarray

In [126]:
c = np.array([1,2,3])

In [127]:
torch.from_numpy(c)

tensor([1, 2, 3])