<a href="https://colab.research.google.com/github/BimalGhimire38/PyTorch_for_deep_learning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2082/05/22  08:27 PM, @Home, Lalitpur

PyTorch Tutorial from YouTube ( [CampusX channel](https://youtu.be/mDsFsnw3SK4))

In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Using GPU: Tesla T4


Creating a Tensor in PyTorch

In [4]:
# Using Empty
a=torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# Using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# Using rand
torch.rand(2,3)

tensor([[0.9166, 0.6671, 0.8822],
        [0.2588, 0.2928, 0.0482]])

In [9]:
# Use of seed
# for Reproduciavility



In [10]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# Other Ways

# arange
print("Using arange ->",torch.arange(0,10,2))

Using arange -> tensor([0, 2, 4, 6, 8])


In [13]:
# Using linspace
print("Using linspace ->",torch.linspace(0,10,10))

Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [14]:
# Using eye
print("Using eye ->", torch.eye(5))

Using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [15]:
# Using full
print("Using full ->",torch.full((3,3),5))

Using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [18]:
x.shape

torch.Size([2, 3])

Creating Similar tensor

In [21]:
y = torch.empty_like(x)
y

tensor([[    140109979299216,     140109979299216,                   0],
        [                  0,                   0, 7310593858020254331]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
# as x has all integer values and rand generates float value between 0 and 1.. It will through an error
# torch.rand_like(x)

In [27]:
x.dtype

torch.int64

In [28]:
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [29]:
torch.tensor([1,2,3,], dtype=torch.float32)

tensor([1., 2., 3.])

Changing the datatype of a datatype

In [31]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [33]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# **Mathematical Opearation in Tensors**

In [34]:
x = torch.rand(2,2)

In [35]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [36]:
# Addition
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [42]:
x

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [37]:
# Subtraction
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [39]:
# multliplication
x*3

tensor([[6.4059, 7.0882],
        [3.7647, 8.1127]])

In [41]:
x

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [40]:
# division
x/3

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [43]:
# Int Division
(x *100)//3

tensor([[71., 78.],
        [41., 90.]])

In [44]:
# mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [45]:
# Power
x**2

tensor([[4.5595, 5.5825],
        [1.5748, 7.3129]])

# Element Wise Operation

In [46]:
a = torch.rand(2,3)
b= torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [51]:
# add
a+b
# subtract
a-b
# division
a/b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [52]:
c = torch.tensor([1,-2,3,-4])

In [53]:
# absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [54]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [55]:
d = torch.tensor([1.9,3.2,4.6,9.8])

In [56]:
# Round
torch.round(d)

tensor([ 2.,  3.,  5., 10.])

In [57]:
# Ceil
torch.ceil(d)

tensor([ 2.,  4.,  5., 10.])

In [60]:
# Floor
torch.floor(d)

tensor([1., 3., 4., 9.])