<a href="https://colab.research.google.com/github/BimalGhimire38/PyTorch_for_deep_learning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2082/05/22  08:27 PM, @Home, Lalitpur

PyTorch Tutorial

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Using GPU: Tesla T4


Creating a Tensor in PyTorch

In [ ]:
# Using Empty
a=torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# Using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Using rand
torch.rand(2,3)

tensor([[0.8263, 0.4542, 0.8548],
        [0.1953, 0.0830, 0.5717]])

In [ ]:
# Use of seed
# for Reproduciavility



In [ ]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Other Ways

# arange
print("Using arange ->",torch.arange(0,10,2))

Using arange -> tensor([0, 2, 4, 6, 8])


In [ ]:
# Using linspace
print("Using linspace ->",torch.linspace(0,10,10))

Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
# Using eye
print("Using eye ->", torch.eye(5))

Using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
# Using full
print("Using full ->",torch.full((3,3),5))

Using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

Creating Similar tensor

In [ ]:
y = torch.empty_like(x)
y

tensor([[              0,       614202464,       661424384],
        [136247596706272,               2,               3]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# as x has all integer values and rand generates float value between 0 and 1.. It will through an error
# torch.rand_like(x)

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3,], dtype=torch.float32)

tensor([1., 2., 3.])

Changing the datatype of a datatype

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# **Mathematical Opearation in Tensors**

In [ ]:
x = torch.rand(2,2)

In [ ]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# Addition
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [ ]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# Subtraction
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [ ]:
# multliplication
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [ ]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# division
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [ ]:
# Int Division
(x *100)//3

tensor([[23., 26.],
        [13., 30.]])

In [ ]:
# mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [ ]:
# Power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

# Element Wise Operation

In [ ]:
a = torch.rand(2,3)
b= torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
# add
a+b
# subtract
a-b
# division
a/b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
# absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9,3.2,4.6,9.8])

In [ ]:
# Round
torch.round(d)

tensor([ 2.,  3.,  5., 10.])

In [ ]:
# Ceil
torch.ceil(d)

tensor([ 2.,  4.,  5., 10.])

In [ ]:
# Floor
torch.floor(d)

tensor([1., 3., 4., 9.])

In [ ]:
# Clamp
torch.clamp(d, min=4, max=5)

tensor([4.0000, 4.0000, 4.6000, 5.0000])

# Reduction Operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [ ]:
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [ ]:
# Sum
torch.sum(e)

tensor(24.)

In [ ]:
# sum along column
torch.sum(e, dim=0)

tensor([ 8.,  0., 16.])

In [ ]:
# sum along row
torch.sum(e, dim=1)

tensor([15.,  9.])

In [ ]:
# Mean
torch.mean(e)

tensor(4.)

In [ ]:
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [ ]:
# Median
torch.median(e)

tensor(0.)

In [ ]:
# Maximum
torch.max(e)

tensor(9.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# Standard Deviation
torch.std(e)

tensor(4.4272)

In [ ]:
# Variance
torch.var(e)

tensor(19.6000)

In [ ]:
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [ ]:
# argmax
torch.argmax(e)

tensor(5)

In [ ]:
# argmin
torch.argmin(e)

tensor(1)

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g= torch.randint(size=(3,2),low=0,high=10)

In [ ]:
f,g

(tensor([[5, 7, 3],
         [9, 4, 0]]),
 tensor([[5, 7],
         [5, 9],
         [9, 7]]))

In [ ]:
# Matrix multliplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

# Vector Operation

In [ ]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])



In [ ]:
v1,v2

(tensor([1, 2]), tensor([3, 4]))

In [ ]:
# dot product
torch.dot(v1,v2)

tensor(11)

In [ ]:
f

tensor([[5, 7, 3],
        [9, 4, 0]])

In [ ]:
# Transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [ ]:
i = torch.randint(size=(3,3),low=2,high=6,dtype=torch.float32)

In [ ]:
i

tensor([[3., 3., 4.],
        [5., 5., 5.],
        [2., 4., 3.]])

In [ ]:
# Determinant
torch.det(i)

tensor(10.)

In [ ]:
# Inverse
torch.inverse(i)

tensor([[-0.5000,  0.7000, -0.5000],
        [-0.5000,  0.1000,  0.5000],
        [ 1.0000, -0.6000,  0.0000]])

[Completed upto this ](https://youtu.be/mDsFsnw3SK4?t=3008)

2082/05/23  08:16 AM

# 5. Comparision Operations

In [ ]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3), low=0, high=10)

In [ ]:
i,j

(tensor([[7, 8, 3],
         [6, 1, 5]]),
 tensor([[5, 0, 4],
         [3, 8, 8]]))

In [ ]:
# greater than
i>j

tensor([[ True,  True, False],
        [ True, False, False]])

In [ ]:
i<j

tensor([[False, False,  True],
        [False,  True,  True]])

In [ ]:
i == j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

# 6. Special Functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10)

In [ ]:
k

tensor([[3, 3, 5],
        [0, 6, 4]])