<a href="https://colab.research.google.com/github/BimalGhimire38/PyTorch_for_deep_learning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2082/05/22  08:27 PM, @Home, Lalitpur

PyTorch Tutorial from YouTube ( [CampusX channel](https://youtu.be/mDsFsnw3SK4))

In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Using GPU: Tesla T4


Creating a Tensor in PyTorch

In [4]:
# Using Empty
a=torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# Using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# Using rand
torch.rand(2,3)

tensor([[0.9166, 0.6671, 0.8822],
        [0.2588, 0.2928, 0.0482]])

In [9]:
# Use of seed
# for Reproduciavility



In [10]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# Other Ways

# arange
print("Using arange ->",torch.arange(0,10,2))

Using arange -> tensor([0, 2, 4, 6, 8])


In [13]:
# Using linspace
print("Using linspace ->",torch.linspace(0,10,10))

Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [14]:
# Using eye
print("Using eye ->", torch.eye(5))

Using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [15]:
# Using full
print("Using full ->",torch.full((3,3),5))

Using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [18]:
x.shape

torch.Size([2, 3])

Creating Similar tensor

In [21]:
y = torch.empty_like(x)
y

tensor([[    140109979299216,     140109979299216,                   0],
        [                  0,                   0, 7310593858020254331]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
# as x has all integer values and rand generates float value between 0 and 1.. It will through an error
# torch.rand_like(x)

In [27]:
x.dtype

torch.int64

In [28]:
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [29]:
torch.tensor([1,2,3,], dtype=torch.float32)

tensor([1., 2., 3.])

Changing the datatype of a datatype

In [31]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])