<a href="https://colab.research.google.com/github/BimalGhimire38/PyTorch_for_deep_learning/blob/main/PyTorch_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NN Module and torch.optim Module , CampusX Video 5

[Video Link](https://youtu.be/CAgWNxlmYsc?list=PLKnIA16_Rmvboy8bmDCjwNHgTaYH2puK7)

2082/08/25, 2025/12/11  07:05 PM , @ Har Har Mahadev , kageshwori Manohara Municipality , Kathmandu Nepal

The torch.mm module in PyTorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks by offering pre-built layers, loss functions, activation functions, and other utilities, enabling you to focus on designing and experimentating with model and architectures.

Key Components of torch.nn:


1.   Module (Layers ):
  nn.Module: The base for all neural network modules. Your custom models and layers should subclass this class.

  Common Layers: Includes layers like nn.Linear(fully connected layer), nn.Conv2d (convolutional layer), nn.LSTM(recurrent layer) , and many other





In [3]:
# create model class
import torch
import torch.nn as nn


class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [4]:
# Create Dataset
features = torch.rand(10,5)

# Create Model
model = Model(features.shape[1])

# Calculate model for forward pass

model(features)

tensor([[0.5472],
        [0.4473],
        [0.5392],
        [0.5790],
        [0.5508],
        [0.4730],
        [0.5430],
        [0.4865],
        [0.4593],
        [0.4149]], grad_fn=<SigmoidBackward0>)

In [5]:
# Show model weights
model.linear.weight

Parameter containing:
tensor([[-0.1801, -0.2834,  0.4446, -0.4149, -0.3490]], requires_grad=True)

In [6]:
model.linear.bias

Parameter containing:
tensor([0.3708], requires_grad=True)

In [7]:
!pip install torchinfo

In [9]:
from torchinfo import summary
summary(model,input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Using Relu function and Hidden Layers

In [11]:
# Create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [12]:
# create dataset

features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

model(features)

tensor([[0.4325],
        [0.4339],
        [0.4339],
        [0.4334],
        [0.4339],
        [0.4339],
        [0.4339],
        [0.4339],
        [0.4339],
        [0.4339]], grad_fn=<SigmoidBackward0>)

In [13]:
model.linear1.weight

Parameter containing:
tensor([[-0.3123, -0.2813, -0.1933, -0.2166, -0.0545],
        [ 0.3213,  0.3767, -0.2065,  0.1125, -0.1700],
        [-0.0879,  0.2717, -0.4180, -0.2000, -0.3024]], requires_grad=True)

In [14]:
model.linear2.weight

Parameter containing:
tensor([[ 0.3607, -0.0786,  0.4727]], requires_grad=True)

In [15]:
from torchinfo import summary

In [16]:
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00